"""Tests for Phase 76 Documentation Compiler."""

import os
from pathlib import Path
import tempfile
import unittest

from framework.core.documentation_compiler import (
    CompiledDocSurface,
    DocCompilationResult,
    DocSurfaceType,
    DocumentationCompiler,
)
from framework.core.manifest import ArtifactOwnership, ArtifactRecord, ProjectManifest, save_manifest


class TestDocumentationCompiler(unittest.TestCase):
    """Test suite for DocumentationCompiler."""

    def test_dry_run_generates_surfaces_without_modifying_disk(self):
        """Dry-run compile generates all surfaces without writing files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = DocumentationCompiler.compile_all_surfaces(tmpdir, dry_run=True)
            self.assertEqual(len(result.applied_files), 0)
            self.assertGreaterEqual(len(result.surfaces), 5)
            # Verify no file written
            self.assertFalse((Path(tmpdir) / "docs" / "architecture").exists())

    def test_preserves_user_authored_documents(self):
        """Compiler skips and refuses to overwrite USER_AUTHORED files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            target = root / "docs" / "architecture" / "ARCHITECTURE_SUMMARY.md"
            target.parent.mkdir(parents=True)
            target.write_text("# User Authored Architecture\nThis is human-owned.", encoding="utf-8")

            # Create manifest marking file as USER_AUTHORED
            manifest = ProjectManifest(
                project_fingerprint="test-fp",
                managed_paths={
                    "docs/architecture/ARCHITECTURE_SUMMARY.md": ArtifactRecord(
                        path="docs/architecture/ARCHITECTURE_SUMMARY.md",
                        ownership=ArtifactOwnership.USER_AUTHORED,
                        sha256="abc",
                        source_revision="rev-1",
                        generated_at="2026-09-01T00:00:00Z",
                    )
                },
            )
            save_manifest(manifest, root)

            result = DocumentationCompiler.compile_all_surfaces(root, dry_run=False)
            self.assertIn("docs/architecture/ARCHITECTURE_SUMMARY.md", result.skipped_user_authored)

            # File content must remain unchanged
            content = target.read_text(encoding="utf-8")
            self.assertIn("User Authored Architecture", content)

    def test_surface_provenance_and_token_bounds(self):
        """Compiled surfaces include provenance headers and remain <= 100 lines."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = DocumentationCompiler.compile_all_surfaces(tmpdir, dry_run=True)
            for surface in result.surfaces:
                self.assertIn("Generated by AntiOS Documentation Compiler", surface.content)
                lines = surface.content.splitlines()
                self.assertLessEqual(
                    len(lines), 100, f"Surface {surface.surface_type.value} exceeds 100 lines."
                )

    def test_protected_documents_never_targeted(self):
        """Compiler must never overwrite protected documents like constitution or active context."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = DocumentationCompiler.compile_all_surfaces(tmpdir, dry_run=True)
            for surface in result.surfaces:
                p = surface.target_rel_path.lower().replace("\\", "/")
                self.assertNotIn("constitution", p)
                self.assertNotIn("active_context", p)


if __name__ == "__main__":
    unittest.main()
